# #
#   Base › Ubuntu › Noble › Docker-compose.yml
#
#   Base docker image for Ubuntu
#
#   @url                  https://github.com/aetherinox/docker-base-ubuntu
#
#   @image:github         ghcr.io/aetherinox/ubuntu:latest
#                         ghcr.io/aetherinox/ubuntu:22.04
#                         ghcr.io/aetherinox/ubuntu:noble
#
#   @image:dockerhub      aetherinox/ubuntu:latest
#                         aetherinox/ubuntu:22.04
#                         aetherinox/ubuntu:noble
# #

services:

    # #
    #   Service › Ubuntu › Noble
    # #

    base-ubuntu-noble:
        container_name: base-ubuntu-noble
        image: noble:latest
        hostname: noble
        environment:
            - TZ=Etc/UTC
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            traefik:
                ipv4_address: '172.18.75.1'

# #
#   Networks
#
#   docker network create --driver=bridge --subnet=172.18.0.0/16 --gateway=172.18.0.1 traefik
# #

networks:
    traefik:
        name: traefik
        external: true
