#!/usr/bin/with-contenv bash
# shellcheck shell=bash

PUID=${PUID:-999}
PGID=${PGID:-999}

# #
#   user information
# #

if [[ -z ${AETHERX_READ_ONLY_FS} ]] && [[ -z ${AETHERX_NON_ROOT_USER} ]]; then
    USERHOME=$( grep dockerx /etc/passwd | cut -d ":" -f6 )
    usermod -d "/root" dockerx > /dev/null

    groupmod -o -g "${PGID}" dockerx > /dev/null
    usermod -o -u "${PUID}" dockerx > /dev/null

    usermod -d "${USERHOME}" dockerx > /dev/null
fi

# #
#   branding
# #

source /etc/s6-overlay/s6-rc.d/init-adduser/branding

# #
#   set ownership perms
# #

if [[ -z ${AETHERX_READ_ONLY_FS} ]] && [[ -z ${AETHERX_NON_ROOT_USER} ]]; then
    aetherxown dockerx:dockerx /app
    aetherxown dockerx:dockerx /config
    aetherxown dockerx:dockerx /defaults
fi
