#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# #
#   define > colors
#
#   Use the color table at:
#       - https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797
# #

declare -A c=(
    [end]=$'\e[0m'
    [white]=$'\e[97m'
    [bold]=$'\e[1m'
    [dim]=$'\e[2m'
    [underline]=$'\e[4m'
    [strike]=$'\e[9m'
    [blink]=$'\e[5m'
    [inverted]=$'\e[7m'
    [hidden]=$'\e[8m'
    [black]=$'\e[0;30m'
    [redl]=$'\e[0;91m'
    [redd]=$'\e[0;31m'
    [magental]=$'\e[0;95m'
    [magentad]=$'\e[0;35mm'
    [bluel]=$'\e[0;94m'
    [blued]=$'\e[0;34m'
    [cyanl]=$'\e[0;96m'
    [cyand]=$'\e[0;36m'
    [greenl]=$'\e[0;92m'
    [greend]=$'\e[0;32m'
    [yellowl]=$'\e[0;93m'
    [yellowd]=$'\e[0;33m'
    [greyl]=$'\e[0;37m'
    [greyd]=$'\e[0;90m'
    [navy]=$'\e[38;5;62m'
    [olive]=$'\e[38;5;144m'
    [peach]=$'\e[38;5;210m'
)

# #
#   unicode for emojis
#       https://apps.timwhitlock.info/emoji/tables/unicode
# #

declare -A icon=(
    ["symbolic link"]=$'\xF0\x9F\x94\x97' # 🔗
    ["regular file"]=$'\xF0\x9F\x93\x84' # 📄
    ["directory"]=$'\xF0\x9F\x93\x81' # 📁
    ["regular empty file"]=$'\xe2\xad\x95' # ⭕
    ["log"]=$'\xF0\x9F\x93\x9C' # 📜
    ["1"]=$'\xF0\x9F\x93\x9C' # 📜
    ["2"]=$'\xF0\x9F\x93\x9C' # 📜
    ["3"]=$'\xF0\x9F\x93\x9C' # 📜
    ["4"]=$'\xF0\x9F\x93\x9C' # 📜
    ["5"]=$'\xF0\x9F\x93\x9C' # 📜
    ["pem"]=$'\xF0\x9F\x94\x92' # 🔑
    ["pub"]=$'\xF0\x9F\x94\x91' # 🔒
    ["pfx"]=$'\xF0\x9F\x94\x92' # 🔑
    ["p12"]=$'\xF0\x9F\x94\x92' # 🔑
    ["key"]=$'\xF0\x9F\x94\x91' # 🔒
    ["crt"]=$'\xF0\x9F\xAA\xAA ' # 🪪
    ["gz"]=$'\xF0\x9F\x93\xA6' # 📦
    ["zip"]=$'\xF0\x9F\x93\xA6' # 📦
    ["gzip"]=$'\xF0\x9F\x93\xA6' # 📦
    ["deb"]=$'\xF0\x9F\x93\xA6' # 📦
    ["sh"]=$'\xF0\x9F\x97\x94' # 🗔
)

# #
#   migrations > define
# #

MIGRATIONS_DIR="/migrations"
MIGRATIONS_HISTORY="/config/.migrations"

# #
#   migrations > start
# #

printf '%-29s %-65s\n' "  ${c[bluel]}Migrations${c[end]}" "${c[end]}Start${c[end]}"

if [[ ! -d ${MIGRATIONS_DIR} ]]; then
    printf '%-29s %-65s\n' "  ${c[bluel]}Migrations${c[end]}" "${c[end]}None found${c[end]}"
    exit
fi

for MIGRATION in $(find ${MIGRATIONS_DIR}/* | sort -n); do
    NAME="$(basename "${MIGRATION}")"
    if [[ -f ${MIGRATIONS_HISTORY} ]] && grep -Fxq "${NAME}" ${MIGRATIONS_HISTORY}; then
        printf '%-29s %-65s\n' "  ${c[bluel]}Migrations${c[end]}" "${c[end]}${NAME} › skipped${c[end]}"
        continue
    fi

    printf '%-29s %-65s\n' "  ${c[bluel]}Migrations${c[end]}" "${c[end]}${NAME} › executing${c[end]}"

    chmod +x "${MIGRATION}"

    # #
    #   Execute migration script in a subshell to prevent it from modifying the current environment
    # #

    ("${MIGRATION}")
    EXIT_CODE=$?
    if [[ ${EXIT_CODE} -ne 0 ]]; then
        printf '%-29s %-65s\n' "  ${c[bluel]}Migrations${c[end]}" "${c[end]}${NAME} › ${c[redl]}failed with exit code ${EXIT_CODE}${c[end]}"
        exit "${EXIT_CODE}"
    fi

    echo "${NAME}" >>${MIGRATIONS_HISTORY}

    printf '%-29s %-65s\n' "  ${c[bluel]}Migrations${c[end]}" "${c[end]}${NAME} › ${c[greenl]}success${c[end]}"
done

# #
#   migrations > finish
# #

printf '%-29s %-65s\n' "  ${c[bluel]}Migrations${c[end]}" "${c[end]}Finished${c[end]}"
